name: catalog-workflow
run-name: Test and deploy catalog on cloud

on:
  push:
    branches: ["catalog"]
  pull_request:
    branches: ["catalog"]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: main-test
      - name: Set up JDK 17 for tests
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Run tests
        working-directory: ${{github.workspace}}/main-test/catalog
        run: mvn test

  build:
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64

      - name: Build with Maven
        working-directory: ${{github.workspace}}/main
        run: mvn clean package -Dmaven.test.skip=true

      - name: Log in to Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.DOCKER_IMAGE_PUSH}}

##      - name: Docker metadata
##        id: meta
##        uses: docker/metadata-action@v5.9.0
##        with:
##          images: ghcr.io/movie-system-backend
##

      - name: Build and upload container image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{github.workspace}}/main/catalog
          push: true
          tags: ghcr.io/${{github.actor}}/catalog:${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy image to Azure
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: movie-catalog
          resourceGroup: movie-apps
          imageToDeploy: ghcr.io/${{ github.actor }}/catalog:${{ github.sha }}
          registryServer: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.READ_PACKAGES }}